---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon-api
  template:
    metadata:
      labels:
        app: pokemon-api
    spec:
      containers:
      - name: pokemon-container
        image: dannylyubenov/pokemon
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-api-service
spec:
  type: NodePort
  selector:
    app: pokemon-api
  ports:
  - name: http
    port: 9090
    targetPort: 80
